/**
 * Every user-facing sentence lives here. Numbers come from the evidence file or from the
 * user's own data and are passed in as arguments; tests reject digits and hype words in this file.
 */
export const APP_NAME = "DataDiet";
export const PAPER_TITLE = "Effects of Data Selection under a Fixed Token Budget";
export const HELPS_SENTENCE =
  "This app helps people fine-tuning a small AI model choose which training examples to use when they can only afford a limited amount of training, based on a controlled study of three selection strategies.";

export const copy = {
  nav: { evidence: "Evidence", how: "How it works", about: "About", start: "Start" },
  landing: {
    title: "Pick the right training examples for your AI",
    subtitle: "Choose fine-tuning data under a limited training budget, using the results of a controlled study.",
    cta: "Try a sample (60 seconds)",
    ctaOwn: "Bring your own data",
    privacy: "Your data never leaves your browser.",
    basedOn: "Based on the study",
    glance: "What the study found",
    glanceNote: "Small model, one training setup. Early results, not a guarantee.",
    stepsTitle: "Three steps",
    steps: [
      { t: "Tell us your goal", d: "Following instructions, reasoning, or math." },
      { t: "Bring your examples", d: "Drop a file or try our sample. We check its health right away." },
      { t: "Get your pick", d: "Compare three ways to choose, then download a ready training file." },
    ],
    tileInstr: "Following instructions",
    tileInstrBody: "A varied pick and a random pick scored about the same.",
    tileReason: "Reasoning puzzles",
    tileReasonBody: "A varied pick scored higher in every protocol we tested.",
    tileMath: "Math word problems",
    tileMathBody: "Higher in most setups, not all.",
    points: "percentage points vs random",
  },
  coach: {
    stepLabels: ["Goal", "Data", "Size", "Pick"],
    goalTitle: "What do you want your model to get better at?",
    goals: {
      instructions: { t: "Follow instructions and formats", e: "Answer in exactly three bullet points." },
      reasoning: { t: "Reason through problems", e: "Which statement must be true?" },
      math: { t: "Solve math word problems", e: "If a train leaves at noon..." },
      unsure: { t: "Not sure", e: "Give me a sensible default." },
    },
    dataTitle: "Bring your examples",
    dropEmpty: "Drop a .jsonl file here, or try our sample.",
    dropHint: "Each line looks like {\"messages\":[{\"role\":\"user\",...},{\"role\":\"assistant\",...}]}",
    browse: "Choose a file",
    sample: "Try a sample",
    paste: "Paste text instead",
    pastePlaceholder: "Paste JSONL here",
    usePasted: "Use pasted text",
    healthy: "Nice, your data looks healthy.",
    worthALook: (n: number) => `We found ${n} ${n === 1 ? "thing" : "things"} worth a look.`,
    usableLine: (usable: number, skipped: number) => `We found ${usable.toLocaleString("en-US")} usable examples. ${skipped.toLocaleString("en-US")} were skipped.`,
    skip: {
      unreadable: "Couldn't read these lines",
      missingRoles: "Missing a user or assistant message",
      tooLong: "Too long for the training window",
      notEnglish: "Not enough English text",
      garbled: "Garbled or repeated characters",
      duplicate: "Duplicate example",
    },
    review: {
      shortAnswer: "Very short answers (worth a look, still used)",
      repeatedChars: "Repeated characters (worth a look, still used)",
    },
    englishOnly: "Some examples aren't in English. This app checks English data only.",
    truncated: "That is a big file. We used the first rows only.",
    tooBig: "That file is too big for a browser. Try a smaller part of it.",
    badFormat: "That file didn't look like JSONL. Here's what a good one looks like.",
    badFormatExample: '{"messages":[{"role":"user","content":"Hi"},{"role":"assistant","content":"Hello!"}]}',
    nothingUsable: "Nothing usable in this file yet. Here's why.",
    tokenizerReal: "Sizes measured with the same tokenizer the study used.",
    tokenizerEstimate: "We couldn't load the exact tokenizer, so sizes are estimates.",
    next: "Continue",
    back: "Back",
    sizeTitle: "How much can you train on?",
    sizeSub: "Measured in tokens (word pieces).",
    presets: { quick: "Quick test", standard: "Standard", study: "Study scale" },
    presetDisabled: "Not enough usable data",
    available: (n: string) => `You can pick up to ${n} tokens from this data.`,
    timeHint: "In the study setup, one million tokens took about half an hour on a single small GPU. Other sizes are rough scaling.",
    run: "Pick my examples",
    running: "Comparing three ways to pick your examples…",
    cancel: "Cancel",
    stages: { reading: "Reading", counting: "Counting", checking: "Checking", picking: "Picking", comparing: "Comparing", downloading: "Downloading model" },
    modelConsent: "To compare “Clean + varied”, we'll download a small model once. It runs in your browser.",
    modelFailed: "The small comparison model couldn't be loaded, so “Clean + varied” was skipped.",
    advanced: "Advanced",
    seed: "Random seed",
    cap: "Candidates per group",
    exactFit: "Fit the budget exactly",
    whitespace: "Keep my formatting (spaces and line breaks)",
    slowPhone: "Comparing can be slow on a phone.",
  },
  policies: {
    random: { name: "Random mix", line: "Picks at random while keeping your mix of sources and lengths." },
    quality: { name: "Cleanest first", line: "Picks the examples with the highest quality score." },
    diversity: { name: "Clean + varied", line: "Groups clean examples by topic, then takes from every group in turn." },
  },
  tiers: {
    "no-gain": { label: "No gain seen", why: "In the study, the intervals for this comparison include zero." },
    promising: { label: "Promising, not proven", why: "Early results from one small model. Worth trying, not a guarantee." },
    unclear: { label: "Unclear", why: "The study can't say yet." },
  },
  verdict: {
    instructions:
      "Fancy selection didn't help here. In the study, a varied pick and a random pick scored about the same. We chose a balanced random set and saved you the extra compute.",
    reasoning: "A varied pick scored higher on reasoning puzzles in the study. Worth trying, but the results are early and come from one small model.",
    mathAll: "Varied picks scored higher on math word problems in every protocol we tested.",
    mathSome: "Varied picks scored higher on math word problems in most setups, but not in every one.",
    unsure: "We went with a varied set. It caused no detectable loss on instruction-following and scored higher on reasoning and math in the study.",
    quality: "No gain over a random pick was seen on any test.",
    ourReading: "Our reading",
    ourReadingTip: "This mapping is our interpretation of the study, not something the paper states.",
    fallbackRandom: "The comparison model wasn't available, so this is a balanced random pick instead.",
  },
  report: {
    headline: (n: number) => `We picked ${n.toLocaleString("en-US")} examples for you.`,
    title: "Your training set report card",
    why: "Why this pick",
    seeEvidence: "See the evidence",
    compare: "Three ways, same budget",
    rows: "Examples",
    used: "Training size (tokens)",
    exact: "Exactly on budget",
    close: "Close to budget",
    topics: "Topics covered",
    recommended: "Our pick",
    showNumbers: "Show the numbers",
    download: "Download training file",
    downloadFor: (name: string) => `Download ${name}`,
    advancedExports: "Advanced exports",
    manifest: "Selection list (CSV)",
    summary: "Run summary (JSON)",
    saveImage: "Save report card as image",
    limits: "What this study can't tell you",
    factRows: "In the study, the same budget gave a different number of examples depending on the strategy.",
    estimateNote: "Sizes were estimated because the exact tokenizer wasn't available. Expect small differences when you train.",
    keepNote: "Your text is exported exactly as written. The study collapsed extra spaces and line breaks first.",
    startOver: "Start over",
    noResult: "There is no result yet. Start with your goal.",
    fillers: "Filler examples added to hit the budget exactly",
  },
  evidence: {
    title: "What the study found",
    intro: "A controlled study compared three ways of choosing training examples under the same token budget.",
    conditions: "Study setup",
    protocolFilter: "Protocol",
    protocols: {
      "primary-2seed": "Main test (two runs)",
      "mixed-3seed": "Three runs (mixed protocol)",
      "expanded-single-seed": "Bigger test set (one run)",
      "seed2026-only": "Third run alone",
    },
    protocolNote: {
      "primary-2seed": "Shorter answers allowed. The protocol fixed before the study.",
      "mixed-3seed": "Pools runs that used different answer-length limits, so read it with care.",
      "expanded-single-seed": "Longer answers allowed, larger test set, one run only.",
      "seed2026-only": "Longer answers allowed, one run only.",
    },
    metrics: {
      ifeval_prompt_strict: "Following instructions",
      ifeval_instruction_strict: "Following instructions (per rule)",
      gsm8k_accuracy: "Math word problems",
      bbh_accuracy: "Reasoning puzzles",
    },
    likelyRange: "likely range",
    likelyRangeTip: "A 95% confidence interval from paired bootstrap resampling of test questions.",
    plotTitle: "Varied pick minus random pick",
    plotAxis: "Percentage points.",
    random_higher: "random pick scored higher",
    varied_higher: "varied pick scored higher",
    cleanest_higher: "cleanest-first pick scored higher",
    qualityTitle: "Cleanest first minus random pick",
    baseTitle: "A note on the untrained model",
    baseBody: "The model without any fine-tuning scored as high or higher than the fine-tuned versions on instructions and math. That is not evidence about the benefit of fine-tuning itself.",
    limitsTitle: "What this study can't tell you",
    limits: [
      "One small model and one training setup.",
      "Test sets are small fixed subsets, so intervals are wide.",
      "Runs used different answer-length limits, and many answers hit the limit.",
      "Only English data, and no human evaluation.",
      "The lowest reasoning subtask scored zero for every strategy.",
    ],
    source: "Source files and checksums",
    paper: "Read the paper (Korean PDF)",
  },
  how: {
    title: "How it works",
    flow: ["Thousands of examples", "Filter out the unusable", "Three ways to pick", "Fill the budget"],
    flowNotes: [
      "Your file, read in your browser.",
      "Unreadable, too long, not English, duplicates.",
      "Random, cleanest first, clean + varied.",
      "Take examples until the token budget is used up.",
    ],
    curious: "For the curious",
    differences: "Differences from the study",
    diffRows: [
      { a: "Quality cutoff", b: "The study's code does not apply the cutoff to Random or to the last top-up step. We follow the code, not the paper text." },
      { a: "Extra spaces", b: "The study collapsed spaces and line breaks. This app keeps yours unless you switch it off." },
      { a: "Topic groups", b: "Clean + varied groups examples with a browser version of k-means. Groups can differ slightly from the study's." },
      { a: "Token counts", b: "Exact only when the study's tokenizer loads. Otherwise estimates." },
    ],
    fidelity: "How closely each strategy matches the study's code",
    fidelityRows: [
      { p: "Random mix", f: "Identical picks in our tests." },
      { p: "Cleanest first", f: "Identical picks in our tests." },
      { p: "Clean + varied", f: "Same procedure. Topic groups are approximate and the embedding model runs in your browser." },
    ],
  },
  about: {
    title: "About",
    body: "DataDiet turns the results of a small controlled study into a tool. It is a learning project, not a product guarantee.",
    privacy: "Privacy",
    privacyBody: "Everything runs in your browser. Your files are never uploaded. The app downloads two small public models from Hugging Face when needed.",
    license: "Licenses and sources",
  },
  errors: {
    generic: "Something went wrong. Nothing was uploaded. Try again, or start over.",
    worker: "The background worker stopped. Your data is still here. Try again.",
  },
  footer: "Made with a study, not a promise.",
} as const;
